//! Exports the Rust-owned wire schema to the TypeScript shared package.
//!
//! Run from the repository root with:
//!
//!     cargo run -p tauri-ui-inspector-core --example export_bindings

#![warn(rust_2018_idioms)]

use std::{env, fs, path::PathBuf};

use tauri_ui_inspector_core::{
    AccessibilityInfo, CaptureInfo, CssRect, CssSize, DomAncestor, DomContext, ElementInfo,
    ElementReference, Locator, LocatorStrategy, PhysicalPoint, PhysicalSize, PickRequestEvent,
    PixelRect, ProjectInfo, ReferenceEvent, ReferenceKind, ResolveRequestEvent, ResolveResult,
    ScreenshotInfo, SelectionPayload, SelectorSummary, SourceComponent, SourceInfo, SourceLocation,
    ViewportInfo, VisualViewportInfo, WindowInfo,
};
use ts_rs::{Config, TS};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..");
    let output = root.join("packages/shared/src/generated.ts");
    let config = Config::default();
    let declarations = [
        CssSize::decl(&config),
        CssRect::decl(&config),
        PhysicalPoint::decl(&config),
        PhysicalSize::decl(&config),
        PixelRect::decl(&config),
        ReferenceKind::decl(&config),
        ProjectInfo::decl(&config),
        ViewportInfo::decl(&config),
        VisualViewportInfo::decl(&config),
        WindowInfo::decl(&config),
        Locator::decl(&config),
        LocatorStrategy::decl(&config),
        SelectorSummary::decl(&config),
        AccessibilityInfo::decl(&config),
        ElementInfo::decl(&config),
        SourceLocation::decl(&config),
        SourceComponent::decl(&config),
        SourceInfo::decl(&config),
        DomAncestor::decl(&config),
        DomContext::decl(&config),
        ScreenshotInfo::decl(&config),
        CaptureInfo::decl(&config),
        SelectionPayload::decl(&config),
        ElementReference::decl(&config),
        PickRequestEvent::decl(&config),
        ResolveRequestEvent::decl(&config),
        ReferenceEvent::decl(&config),
        ResolveResult::decl(&config),
    ]
    .into_iter()
    .map(|declaration| format!("export {declaration}"))
    .collect::<Vec<_>>()
    .join("\n\n");
    if let Some(parent) = output.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(
        output,
        format!(
            "// Generated by `cargo run -p tauri-ui-inspector-core --example export_bindings`.\n\n{declarations}\n"
        ),
    )?;
    Ok(())
}
