// Generated by `cargo run -p tauri-ui-inspector-core --example export_bindings`.

export type CssSize = { 
/**
 * Width in CSS pixels.
 */
width: number, 
/**
 * Height in CSS pixels.
 */
height: number, };

export type CssRect = { 
/**
 * Alias of `left`, retained for `DOMRect` compatibility.
 */
x: number, 
/**
 * Alias of `top`, retained for `DOMRect` compatibility.
 */
y: number, 
/**
 * Width in CSS pixels.
 */
width: number, 
/**
 * Height in CSS pixels.
 */
height: number, 
/**
 * Top edge in CSS viewport coordinates.
 */
top: number, 
/**
 * Right edge in CSS viewport coordinates.
 */
right: number, 
/**
 * Bottom edge in CSS viewport coordinates.
 */
bottom: number, 
/**
 * Left edge in CSS viewport coordinates.
 */
left: number, };

export type PhysicalPoint = { 
/**
 * Horizontal coordinate.
 */
x: number, 
/**
 * Vertical coordinate.
 */
y: number, };

export type PhysicalSize = { 
/**
 * Width in native units.
 */
width: number, 
/**
 * Height in native units.
 */
height: number, };

export type PixelRect = { 
/**
 * Left pixel in the image.
 */
x: number, 
/**
 * Top pixel in the image.
 */
y: number, 
/**
 * Pixel width.
 */
width: number, 
/**
 * Pixel height.
 */
height: number, };

export type ReferenceKind = "element" | "group" | "region";

export type ProjectInfo = { 
/**
 * Project root recorded by the plugin, when configured.
 */
root?: string | null, };

export type ViewportInfo = { 
/**
 * Layout viewport size in CSS pixels.
 */
size: CssSize, 
/**
 * Browser-reported device pixel ratio.
 */
devicePixelRatio: number, 
/**
 * Visual viewport data when supported by the webview.
 */
visualViewport?: VisualViewportInfo | null, };

export type VisualViewportInfo = { 
/**
 * Horizontal layout-viewport offset in CSS pixels.
 */
offsetLeft: number, 
/**
 * Vertical layout-viewport offset in CSS pixels.
 */
offsetTop: number, 
/**
 * Visual viewport scale.
 */
scale: number, 
/**
 * Visual viewport width in CSS pixels.
 */
width: number, 
/**
 * Visual viewport height in CSS pixels.
 */
height: number, };

export type WindowInfo = { 
/**
 * Tauri window label.
 */
label: string, 
/**
 * Native window title.
 */
title?: string | null, 
/**
 * Tauri scale factor at capture time.
 */
scaleFactor: number, 
/**
 * Native outer-window position.
 */
outerPosition: PhysicalPoint, 
/**
 * Native content-area position.
 */
innerPosition: PhysicalPoint, 
/**
 * Native outer-window size.
 */
outerSize: PhysicalSize, 
/**
 * Native content-area size.
 */
innerSize: PhysicalSize, 
/**
 * Browser viewport metrics.
 */
viewport: ViewportInfo, };

export type Locator = { 
/**
 * Locator strategy.
 */
strategy: LocatorStrategy, 
/**
 * Primary locator value.
 */
value: string, 
/**
 * Attribute name for attribute-based locators.
 */
attribute?: string | null, 
/**
 * Accessible name for role locators.
 */
name?: string | null, 
/**
 * Deterministic confidence score between 0 and 1.
 */
confidence: number, 
/**
 * Whether the locator was unique at selection time.
 */
unique: boolean, };

export type LocatorStrategy = "testId" | "role" | "id" | "attribute" | "source" | "css" | "domPath" | "text";

export type SelectorSummary = { 
/**
 * Highest-confidence selector-like value.
 */
preferred?: string | null, 
/**
 * Generated CSS selector.
 */
css?: string | null, 
/**
 * Explicit test identifier.
 */
testId?: string | null, 
/**
 * Unique element id.
 */
id?: string | null, 
/**
 * Semantic role.
 */
role?: string | null, 
/**
 * Short normalized text.
 */
text?: string | null, };

export type AccessibilityInfo = { 
/**
 * Computed semantic role.
 */
role?: string | null, 
/**
 * Computed accessible name.
 */
name?: string | null, 
/**
 * Computed accessible description.
 */
description?: string | null, 
/**
 * `aria-label` value.
 */
ariaLabel?: string | null, 
/**
 * `aria-labelledby` token list.
 */
ariaLabelledBy?: string | null, 
/**
 * `aria-describedby` token list.
 */
ariaDescribedBy?: string | null, 
/**
 * Disabled state.
 */
disabled?: boolean | null, 
/**
 * Checked state.
 */
checked?: boolean | null, 
/**
 * Selected state.
 */
selected?: boolean | null, 
/**
 * Expanded state.
 */
expanded?: boolean | null, 
/**
 * Pressed state.
 */
pressed?: boolean | null, 
/**
 * Placeholder text.
 */
placeholder?: string | null, 
/**
 * Associated form label.
 */
formLabel?: string | null, 
/**
 * Form control input type.
 */
inputType?: string | null, 
/**
 * Form value, present only when explicitly allowed and not sensitive.
 */
value?: string | null, };

export type ElementInfo = { 
/**
 * Lowercase DOM tag name.
 */
tagName: string, 
/**
 * Namespace URI for SVG and other non-HTML elements.
 */
namespace?: string | null, 
/**
 * Short normalized visible text.
 */
text?: string | null, 
/**
 * Computed semantic role.
 */
role?: string | null, 
/**
 * Computed accessible name.
 */
accessibleName?: string | null, 
/**
 * Selected attributes after redaction.
 */
attributes: { [key in string]: string }, 
/**
 * Element rectangle in CSS viewport coordinates.
 */
rect: CssRect, 
/**
 * Stable locators ordered from strongest to weakest.
 */
locators: Array<Locator>, 
/**
 * Convenient top-ranked selectors.
 */
selectors: SelectorSummary, 
/**
 * Accessibility metadata.
 */
accessibility: AccessibilityInfo, };

export type SourceLocation = { 
/**
 * Source file path as emitted by the framework toolchain.
 */
file: string, 
/**
 * One-based source line when available.
 */
line?: number | null, 
/**
 * One-based source column when available.
 */
column?: number | null, };

export type SourceComponent = { 
/**
 * Framework component name.
 */
component?: string | null, 
/**
 * Component source location.
 */
location: SourceLocation, };

export type SourceInfo = { 
/**
 * Framework adapter name.
 */
framework: string, 
/**
 * Closest component name.
 */
component?: string | null, 
/**
 * Closest source location.
 */
location: SourceLocation, 
/**
 * Parent component frames, nearest first.
 */
ancestry: Array<SourceComponent>, };

export type DomAncestor = { 
/**
 * Lowercase tag name.
 */
tagName: string, 
/**
 * Unique id when present.
 */
id?: string | null, 
/**
 * Short class list.
 */
classes: Array<string>, 
/**
 * Semantic role.
 */
role?: string | null, 
/**
 * Accessible name.
 */
accessibleName?: string | null, };

export type DomContext = { 
/**
 * Sanitized, truncated selected-element HTML.
 */
html: string, 
/**
 * Sanitized, truncated parent HTML.
 */
parentHtml?: string | null, 
/**
 * Ancestors from parent to root, capped by the frontend.
 */
ancestry: Array<DomAncestor>, };

export type ScreenshotInfo = { 
/**
 * Full native window screenshot.
 */
window?: string | null, 
/**
 * Selected element crop.
 */
element?: string | null, };

export type CaptureInfo = { 
/**
 * Padding applied around the element in CSS pixels.
 */
padding: number, 
/**
 * Pixel crop within `window.png`.
 */
pixelCrop?: PixelRect | null, 
/**
 * Actual screenshot bitmap size.
 */
screenshotSize?: PhysicalSize | null, };

export type SelectionPayload = { 
/**
 * Browser viewport metrics.
 */
viewport: ViewportInfo, 
/**
 * Selected element metadata.
 */
element: ElementInfo, 
/**
 * Optional source metadata.
 */
source?: SourceInfo | null, 
/**
 * Bounded DOM context.
 */
dom: DomContext, };

export type ElementReference = { 
/**
 * Schema version used to serialize this reference.
 */
schemaVersion: number, 
/**
 * Captured subject type.
 */
kind: ReferenceKind, 
/**
 * Opaque `ui_<ULID>` identifier.
 */
id: string, 
/**
 * RFC 3339 timestamp.
 */
createdAt: string, 
/**
 * Deterministic, agent-oriented summary.
 */
summary: string, 
/**
 * Project metadata.
 */
project: ProjectInfo, 
/**
 * Window and viewport metadata.
 */
window: WindowInfo, 
/**
 * Selected element metadata.
 */
element: ElementInfo, 
/**
 * Optional framework source mapping.
 */
source?: SourceInfo | null, 
/**
 * Bounded DOM context.
 */
dom: DomContext, 
/**
 * Screenshot filenames.
 */
screenshots: ScreenshotInfo, 
/**
 * Native capture geometry.
 */
capture: CaptureInfo, };

export type PickRequestEvent = { 
/**
 * Pending backend operation identifier.
 */
requestId: string, };

export type ResolveRequestEvent = { 
/**
 * Pending backend operation identifier.
 */
requestId: string, 
/**
 * Stored reference to reacquire.
 */
reference: ElementReference, };

export type ReferenceEvent = { 
/**
 * Created reference.
 */
reference: ElementReference, };

export type ResolveResult = { "status": "resolved", 
/**
 * Locator strategy that matched.
 */
locatorIndex: number, 
/**
 * Fresh element rectangle.
 */
rect: CssRect, } | { "status": "notFound", 
/**
 * Deterministic failure explanation.
 */
reason: string, };
